<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ServiceCategory;
use App\Models\ServiceUnit;
use App\Models\LabService;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class LabTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $tenant = app('currentTenant');

        $serviceUnit = ServiceUnit::where('name', 'Laboratory')->first();
        $clinicalChemistryCategory = ServiceCategory::where('name', 'CLINICAL CHEMISTRY')->first();
        $haematologyCategory = ServiceCategory::where('name', 'HAEMATOLOGY')->first();
        $lipidProfileCategory = ServiceCategory::where('name', 'LIPID PROFILE')->first();
        $endocrinologyCategory = ServiceCategory::where('name', 'ENDOCRINOLOGY')->first();
        $microbiologyCategory = ServiceCategory::where('name', 'MICROBIOLOGY')->first();
        $prenatalCategory = ServiceCategory::where('name', 'PRENATAL SCREENING')->first();
        $immunologyCategory = ServiceCategory::where('name', 'IMMUNOLOGY')->first();
        $tumorMarkersCategory = ServiceCategory::where('name', 'TUMOR MARKERS')->first();
        $serologyCategory = ServiceCategory::where('name', 'SEROLOGY')->first();
        $urinalysisCategory = ServiceCategory::where('name', 'URINALYSIS')->first();

        $labTest = [
            'CLINICAL CHEMISTRY' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Basic Metabolic Panel (BMP)', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Electrolytes Urea and Creatinine (E/U/Cr)', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Electrolytes Panel', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Glucose & Diabetes Tests', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Liver Function Tests (LFTs)', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Cardiac Markers', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Pancreatic Enzymes', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Iron Studies & Vitamins', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Minerals & Uric Acid', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $clinicalChemistryCategory->id, 'name' => 'Blood Gas Analysis', 'class' => $clinicalChemistryCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
            ],
            'HAEMATOLOGY' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Full Blood Count (FBC)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Hemoglobin (Hb)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Hematocrit (PCV)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Platelet Count', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Reticulocyte Count', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Erythrocyte Sedimentation Rate (ESR)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Peripheral Blood Smear - (Descriptive)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Blood Typing (ABO and Rh)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Genotype', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Cross Match', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Direct Coombs Test', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Indirect Coombs Test', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'G6PD Screening', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Sickling Test', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Prothrombin Time (PT)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Activated Partial Thromboplastin Time (aPTT)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'D-Dimer', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Fibrinogen Level', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Bleeding Time', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Clotting Time', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'White Blood Cell Count (WBC)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $haematologyCategory->id, 'name' => 'Red Blood Cell Count (RBC)', 'class' => $haematologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
            ],

            'LIPID PROFILE' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $lipidProfileCategory->id, 'name' => 'Lipid Panel (Complete)', 'class' => $lipidProfileCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $lipidProfileCategory->id, 'name' => 'Total Cholesterol', 'class' => $lipidProfileCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $lipidProfileCategory->id, 'name' => 'Low-Density Lipoprotein (LDL)', 'class' => $lipidProfileCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $lipidProfileCategory->id, 'name' => 'High-Density Lipoprotein (HDL)', 'class' => $lipidProfileCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $lipidProfileCategory->id, 'name' => 'Triglycerides', 'class' => $lipidProfileCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $lipidProfileCategory->id, 'name' => 'VLDL Cholesterol', 'class' => $lipidProfileCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $lipidProfileCategory->id, 'name' => 'Cholesterol/HDL Ratio', 'class' => $lipidProfileCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $lipidProfileCategory->id, 'name' => 'Lipoprotein(a)', 'class' => $lipidProfileCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
            ],

            'ENDOCRINOLOGY' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Thyroid Stimulating Hormone (TSH)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Free Triiodothyronine (Free T3)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Free Thyroxine (Free T4)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Total T3', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Total T4', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Thyroid Antibodies (Anti-TPO)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Thyroglobulin', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Cortisol (Morning)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Cortisol (Evening)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'ACTH (Adrenocorticotropic Hormone)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Growth Hormone (GH)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'IGF-1 (Insulin-like Growth Factor 1)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Prolactin', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Follicle Stimulating Hormone (FSH)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Luteinizing Hormone (LH)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Estradiol', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Progesterone', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Testosterone (Total)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Testosterone (Free)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'DHEA-Sulfate (DHEAS)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Androstenedione', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Parathyroid Hormone (PTH)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Insulin', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'C-Peptide', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Prostate Specific Antigen (PSA)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Glycated Hemoglobin (HbA1c)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $endocrinologyCategory->id, 'name' => 'Thyroid Function Tests (TFTs)', 'class' => $endocrinologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
            ],

            'MICROBIOLOGY' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Blood Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Urine Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Sputum Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Wound Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Throat Swab Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Ear Swab Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Eye Swab Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'High Vaginal Swab Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Urethral Swab Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Cerebrospinal Fluid (CSF) Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'GeneXpert MTB/RIF', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Helicobacter Pylori Stool Antigen', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'KOH Preparation', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'AFB (Acid Fast Bacilli) Smear', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Stool Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Nasal Swab Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $microbiologyCategory->id, 'name' => 'Genital Swab Culture', 'class' => $microbiologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
            ],

            'PRENATAL SCREENING' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Beta-hCG (Quantitative)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Pregnancy Test (Serum)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Pregnancy Test (Urine)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'PAPP-A (Pregnancy-Associated Plasma Protein A)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Triple Screen', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Quadruple Screen', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'TORCH Panel', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Group B Streptococcus (GBS) Screen', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Rh Antibody Screen', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Glucose Challenge Test (GCT)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Oral Glucose Tolerance Test (OGTT) – Pregnancy', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'AFP (Alpha-Fetoprotein)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Inhibin A', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Unconjugated Estriol (uE3)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Cell-Free Fetal DNA Testing (NIPT)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'First Trimester Combined Screening (NT + PAPP-A + Free β-hCG)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Second Trimester Quadruple Screening (AFP + hCG + Estriol + Inhibin A)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Maternal Serum Screening (MSS)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Fetal Fibronectin (fFN) Test', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Amniocentesis', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Chorionic Villus Sampling (CVS)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Non-Stress Test (NST)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Biophysical Profile (BPP)', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Fetal Kick Count', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $prenatalCategory->id, 'name' => 'Fetal Heart Rate Monitoring', 'class' => $prenatalCategory->name, 'price' => 0.00, 'type' => 'Antenatal', 'created_at' => $now, 'updated_at' => $now]
            ],

            'IMMUNOLOGY' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Rheumatoid Factor (RF)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'C-Reactive Protein (CRP)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'High Sensitivity CRP (hs-CRP)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Complement Levels (C3)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Complement Levels (C4)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Total IgE', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Immunoglobulin G (IgG)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Immunoglobulin A (IgA)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Immunoglobulin M (IgM)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Serum Protein Electrophoresis (SPEP)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Antinuclear Antibody (ANA)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Erythrocyte Sedimentation Rate (ESR)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-CCP (Cyclic Citrullinated Peptide) Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-dsDNA (Double-Stranded DNA) Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-Smith Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-Ro (SSA) Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-La (SSB) Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-Jo-1 Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-Scl-70 (Topoisomerase I) Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-Centromere Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-Histone Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-RNP (Ribonucleoprotein) Antibody', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $immunologyCategory->id, 'name' => 'Anti-Phospholipid Antibodies (Lupus Anticoagulant, Anti-cardiolipin, Anti-β2 Glycoprotein I)', 'class' => $immunologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now]
            ],

            'TUMOR MARKERS' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Alpha-Fetoprotein (AFP)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Carcinoembryonic Antigen (CEA)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Cancer Antigen 19-9 (CA 19-9)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Cancer Antigen 125 (CA-125)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Cancer Antigen 125 (CA-15-3)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Cancer Antigen 125 (CA-27-29)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Prostate Specific Antigen (PSA)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Free PSA', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Beta-2 Microglobulin', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Chromogranin A', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Human Chorionic Gonadotropin (hCG)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Lactate Dehydrogenase (LDH)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'S100 Protein', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Neuron-Specific Enolase (NSE)', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Thyroglobulin', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $tumorMarkersCategory->id, 'name' => 'Calcitonin', 'class' => $tumorMarkersCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now]
            ],

            'SEROLOGY' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'HIV Screening (Reactive/Non-Reactive)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'HIV 1/2 Confirmation Test (Positive/Negative)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'HIV Viral Load', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'HIV 1/2 Antibody', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'CD4 Count', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Hepatitis A IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Hepatitis A IgG', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Hepatitis B Surface Antigen (HBsAg)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Hepatitis B Panel Test', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Hepatitis B Viral Load', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Hepatitis C Antibody (Anti-HCV)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Hepatitis C Viral Load (PCR)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Hepatitis A Antibody (Anti-HAV)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Hepatitis E Antibody (Anti-HEV)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Syphilis Screen (RPR or VDRL)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'TPHA / FTA-ABS (Syphilis Confirmation Test)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Toxoplasma Gondii IgG', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Toxoplasma Gondii IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Rubella IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Rubella IgG', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Cytomegalovirus (CMV) IgG', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Cytomegalovirus (CMV) IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Epstein-Barr Virus (EBV) VCA IgG', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Epstein-Barr Virus (EBV) VCA IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Herpes Simplex Virus (HSV) IgG', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Herpes Simplex Virus (HSV) IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Varicella-Zoster Virus (VZV) IgG', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Varicella-Zoster Virus (VZV) IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Helicobacter Pylori Antibody', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Dengue NS1 Antigen', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Dengue IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Dengue IgG', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Malaria Rapid Test', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Malaria Parasite (Blood Film)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Typhoid (Widal Test)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Typhoid IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'COVID-19 RT-PCR', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'COVID-19 Rapid Antigen', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'COVID-19 Antibody (IgG/IgM)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Treponema Pallidum Particle Agglutination (TPPA)', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Parvovirus B19 IgG and IgM', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Leptospirosis Serology', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Brucellosis Serology', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Q Fever Serology', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Leishmaniasis Serology', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Chagas Disease Serology', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $serologyCategory->id, 'name' => 'Leprosy Serology', 'class' => $serologyCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now]
            ],
            'URINALYSIS' => [
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $urinalysisCategory->id, 'name' => 'Urinalysis (Complete)', 'class' => $urinalysisCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $urinalysisCategory->id, 'name' => 'Urinalysis (Dipstick Only)', 'class' => $urinalysisCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
                ['tenant_id' => $tenant->uuid, 'service_unit_id' => $serviceUnit->id, 'service_category_id' => $urinalysisCategory->id, 'name' => 'Urine Microscopy (M/C/S)', 'class' => $urinalysisCategory->name, 'price' => 0.00, 'type' => 'General', 'created_at' => $now, 'updated_at' => $now],
            ],
        ];

        $allTests = array_merge(...array_values($labTest));
        foreach ($allTests as $test) {
            LabService::firstOrCreate(
                ['name' => $test['name'], 'tenant_id' => $test['tenant_id']],
                $test
            );
        }
    }
}
