<?php

namespace App\Services\Payment;

use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

/**
 * Class PaystackService
 *
 * The only place in the application that talks to Paystack.
 *
 * Everything above it — a patient paying a bill, a friend contributing through a
 * shared link, a hospital saving the account it is settled into — goes through
 * these methods, so the secret key, the money-to-kobo conversion and the shape
 * of a Paystack error are each handled once instead of at every call site.
 *
 * Amounts cross this boundary in naira and are converted to kobo here, because
 * getting that wrong is a hundred-fold mistake and it should only be possible to
 * make it in one file.
 */
class PaystackService
{
    /**
     * Whether the platform has been given keys at all.
     *
     * Checked before anything is written, so a hospital or a patient is told
     * that online payment is not switched on rather than watching a request to
     * Paystack come back 401.
     */
    public function isConfigured(): bool
    {
        return !empty(config('services.paystack.secret_key'));
    }

    /**
     * Start a checkout and get back the page to send the payer to.
     *
     * The reference is generated by us rather than by Paystack, so the payment
     * row exists — and is verifiable — before the payer ever leaves. The
     * subaccount is what makes the split happen: Paystack settles the hospital's
     * share to their own bank and leaves the platform commission behind.
     *
     * @param  array<string, mixed>  $payload
     * @return array<string, mixed>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    public function initializeTransaction(array $payload): array
    {
        $body = array_filter([
            'email' => $payload['email'],
            'amount' => $this->toKobo($payload['amount']),
            'reference' => $payload['reference'],
            'currency' => $payload['currency'] ?? config('services.paystack.currency'),
            'channels' => $payload['channels'] ?? config('services.paystack.channels'),
            'callback_url' => $payload['callback_url'] ?? config('services.paystack.callback_url'),
            'subaccount' => $payload['subaccount'] ?? null,

            // Charging the fee to the platform rather than to the subaccount is
            // what keeps the hospital's share exactly the amount on the invoice.
            'bearer' => !empty($payload['subaccount']) ? 'account' : null,
            'metadata' => $payload['metadata'] ?? null,
        ], fn($value) => $value !== null && $value !== []);

        return $this->post('/transaction/initialize', $body);
    }

    /**
     * Ask Paystack what became of a reference.
     *
     * This is how a payment is confirmed. There is no webhook, so nothing is
     * ever marked paid on the strength of the payer having been redirected
     * back. Safe to call repeatedly: verification is a read.
     *
     * @return array<string, mixed>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    public function verifyTransaction(string $reference): array
    {
        return $this->get('/transaction/verify/' . rawurlencode($reference));
    }

    /**
     * The banks a hospital can pick from when saying where it is settled.
     *
     * @return array<int, array<string, mixed>>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    public function listBanks(?string $country = null): array
    {
        $response = $this->get('/bank', [
            'country' => $country ?: 'nigeria',
            'perPage' => 100,
        ]);

        return $response['data'] ?? [];
    }

    /**
     * Turn a bank and an account number into the name the bank holds for it.
     *
     * Called before the account is saved, so what a hospital stores is the name
     * the bank returned rather than one somebody typed. A transposed digit is
     * then caught at the point of entry instead of at the first settlement.
     *
     * @return array<string, mixed>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    public function resolveAccountNumber(string $accountNumber, string $bankCode): array
    {
        $response = $this->get('/bank/resolve', [
            'account_number' => $accountNumber,
            'bank_code' => $bankCode,
        ]);

        return $response['data'] ?? [];
    }

    /**
     * Register a hospital as a subaccount so charges can be split to it.
     *
     * @param  array<string, mixed>  $payload
     * @return array<string, mixed>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    public function createSubaccount(array $payload): array
    {
        $response = $this->post('/subaccount', $this->subaccountBody($payload));

        return $response['data'] ?? [];
    }

    /**
     * Move an existing subaccount onto new bank details or a new share.
     *
     * @param  array<string, mixed>  $payload
     * @return array<string, mixed>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    public function updateSubaccount(string $subaccountCode, array $payload): array
    {
        $response = $this->put('/subaccount/' . rawurlencode($subaccountCode), $this->subaccountBody($payload));

        return $response['data'] ?? [];
    }

    /**
     * A reference nothing else will collide with.
     *
     * Prefixed so a glance at the Paystack dashboard says which flow a charge
     * came from without anyone having to open it.
     */
    public function generateReference(string $prefix = 'EMED'): string
    {
        return strtoupper($prefix . '-' . now()->format('YmdHis') . '-' . Str::random(8));
    }

    /**
     * Naira to kobo, which is the only unit Paystack accepts.
     *
     * Rounded before the cast: 250.10 lands on 25009.999... in binary floating
     * point, and an int cast of that would quietly undercharge by a kobo.
     */
    public function toKobo(float|int|string $amount): int
    {
        return (int) round(((float) $amount) * 100);
    }

    /**
     * Kobo back to naira, for reading Paystack's side of a verification.
     */
    public function toNaira(int|float|string $amount): float
    {
        return round(((float) $amount) / 100, 2);
    }

    /**
     * The body both subaccount calls send.
     *
     * @param  array<string, mixed>  $payload
     * @return array<string, mixed>
     */
    protected function subaccountBody(array $payload): array
    {
        return array_filter([
            'business_name' => $payload['business_name'],
            'settlement_bank' => $payload['bank_code'],
            'account_number' => $payload['account_number'],
            'percentage_charge' => $payload['percentage_charge'],
            'primary_contact_email' => $payload['email'] ?? null,
            'primary_contact_phone' => $payload['phone'] ?? null,
        ], fn($value) => $value !== null);
    }

    /**
     * @return array<string, mixed>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    protected function get(string $path, array $query = []): array
    {
        return $this->send('get', $path, $query);
    }

    /**
     * @return array<string, mixed>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    protected function post(string $path, array $body = []): array
    {
        return $this->send('post', $path, $body);
    }

    /**
     * @return array<string, mixed>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    protected function put(string $path, array $body = []): array
    {
        return $this->send('put', $path, $body);
    }

    /**
     * One request, and one place where a failure becomes a PaystackException.
     *
     * Paystack answers with a false status and a readable message for the things
     * a caller can act on, and with an HTTP error for the things it cannot, so
     * both are folded into the same exception here.
     *
     * @param  array<string, mixed>  $data
     * @return array<string, mixed>
     *
     * @throws \App\Services\Payment\PaystackException
     */
    protected function send(string $method, string $path, array $data): array
    {
        if (!$this->isConfigured()) {
            throw new PaystackException('Online payment has not been set up on this platform yet.', [], 503);
        }

        try {
            $response = $this->client()->{$method}($path, $data);
        } catch (\Throwable $th) {
            // A timeout or a DNS failure. Logged with the path but never with
            // the body, which carries the payer's email address.
            Log::error('Could not reach Paystack.', [
                'method' => $method,
                'path' => $path,
                'exception' => $th->getMessage(),
            ]);

            throw new PaystackException('We could not reach the payment provider. Please try again.', [], 503);
        }

        $body = $response->json() ?? [];

        if (!$response->successful() || ($body['status'] ?? false) !== true) {
            $message = $body['message'] ?? 'The payment provider rejected that request.';

            Log::warning('Paystack rejected a request.', [
                'method' => $method,
                'path' => $path,
                'http_status' => $response->status(),
                'message' => $message,
            ]);

            throw new PaystackException($message, $body, 422);
        }

        return $body;
    }

    /**
     * A configured HTTP client.
     *
     * Deliberately not retried: a repeated initialize would leave a second
     * charge waiting against the same bill.
     */
    protected function client(): PendingRequest
    {
        return Http::withToken(config('services.paystack.secret_key'))
            ->baseUrl(rtrim(config('services.paystack.base_url'), '/'))
            ->timeout(config('services.paystack.timeout', 30))
            ->acceptJson()
            ->asJson();
    }
}
